[package]
name = "type-per-file-lint"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
dylint_linting = "5"
heck = "0.5"

[dev-dependencies]
dylint_testing = "5"
