name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
env:
  CARGO_TERM_COLOR: always
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt
      - run: cargo +nightly fmt -- --check
  test:
    name: test
    runs-on: ubuntu-latest
    needs:
      - no-std
      - embassy
    steps:
      - uses: actions/checkout@v5
      - uses: arduino/setup-protoc@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - run: cargo test --verbose
  no-std:
    name: no-std
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - run: cargo check -p cellex-utils-core-rs --no-default-features --features alloc
  embassy:
    name: embassy
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - run: cargo test -p cellex-utils-embedded-rs --no-default-features --features embassy --no-run
