name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt
      - run: ./scripts/ci-check.sh lint
  no-std:
    name: no-std
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: ./scripts/ci-check.sh no-std
  embedded:
    name: embedded
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add thumbv6m-none-eabi thumbv8m.main-none-eabi
      - run: ./scripts/ci-check.sh embedded
  std:
    name: std
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - run: ./scripts/ci-check.sh std
  test:
    name: test
    runs-on: ubuntu-latest
    needs:
      - no-std
      - std
      - embedded
    steps:
      - uses: actions/checkout@v5
      - uses: arduino/setup-protoc@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: ./scripts/ci-check.sh test
